version: '3'

services:
  api:
    build:
        context: .
        args:
          API_VERSION: 1        
    restart: always
    hostname: arridle
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:arridle.rezoleo.fr"
      - "traefik.port=8000"
      - "traefik.network=proxy"
    volumes:
      - "/home/divers/ctf/writable/web1:/var/www/html/"

networks:
  proxy:
    external: true
